controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base
      - shoulder
      - elbow
      - wrist_pitch
      - wrist_roll
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_movable
initial:  # Define initial robot poses per group
  - group: arm
    pose: basic